version: "3"
services:
  job:
    image: 
    # environment:
    #   - 
    ports:
      - 8000:8000
    logging:
      driver: awslogs
      options:
        awslogs-group: "/ecs/job-development"
        awslogs-region: "ap-northeast-2"
        awslogs-stream-prefix: "dev"
