version: "3"
services:
  job:
    image: 
    # environment:
    #   - 
    ports:
      - 8000:8000
    logging:
      driver: awslogs
      options:
        awslogs-group: "/ecs/job-staging"
        awslogs-region: "ap-southeast-1"
        awslogs-stream-prefix: "stg"
